In [3]:
import pandas as pd

In [37]:
geographies = {"State": [], "Region": []}

In [38]:
# South = ["AR","LA","MS","TN","AL","KY","WV","VA","GA","FL","SC","NC"]
# SouthWest = ["NV","AZ","NM","TX"]
# West_Coast = ["CA","OR","WA"]
# Mountain = ["ID","UT","CO","WY","MT"]
# Plains = ["ND","SD","NE","KS","OK"]
# MidWest = ["MN","IA","MO","WI","MI","IL","OH","IN"]
# NorthEast = ["PA","NY","MD","DE","NJ","DC","CT","RI","MA","VT","ME","NH"]

geographies_1 = {"South":["AR","LA","MS","TN","AL","KY","WV","VA","GA","FL","SC","NC"],
                 "SouthWest":["NV","AZ","NM","TX"], 
                 "West_Coast":["CA","OR","WA","HI","AK"],
                 "Mountain": ["ID","UT","CO","WY","MT"],
                 "Plains": ["ND","SD","NE","KS","OK"],
                 "MidWest": ["MN","IA","MO","WI","MI","IL","OH","IN"],
                 "NorthEast": ["PA","NY","MD","DE","NJ","DC","CT","RI","MA","VT","ME","NH"]}

In [39]:
Regions = ["South","SouthWest","West_Coast","Mountain","Plains","MidWest","NorthEast"]

In [40]:
for key in geographies_1:
#     print(key)
#     print(geographies_1[key])
    for state in geographies_1[key]:
        geographies["State"].append(state)
        print(state)
        geographies["Region"].append(key)
        print(key)

AR
South
LA
South
MS
South
TN
South
AL
South
KY
South
WV
South
VA
South
GA
South
FL
South
SC
South
NC
South
NV
SouthWest
AZ
SouthWest
NM
SouthWest
TX
SouthWest
CA
West_Coast
OR
West_Coast
WA
West_Coast
HI
West_Coast
AK
West_Coast
ID
Mountain
UT
Mountain
CO
Mountain
WY
Mountain
MT
Mountain
ND
Plains
SD
Plains
NE
Plains
KS
Plains
OK
Plains
MN
MidWest
IA
MidWest
MO
MidWest
WI
MidWest
MI
MidWest
IL
MidWest
OH
MidWest
IN
MidWest
PA
NorthEast
NY
NorthEast
MD
NorthEast
DE
NorthEast
NJ
NorthEast
DC
NorthEast
CT
NorthEast
RI
NorthEast
MA
NorthEast
VT
NorthEast
ME
NorthEast
NH
NorthEast

In [43]:
df_geography = pd.DataFrame(geographies)
df_geography

   State      Region
0     AR       South
1     LA       South
2     MS       South
3     TN       South
4     AL       South
5     KY       South
6     WV       South
7     VA       South
8     GA       South
9     FL       South
10    SC       South
11    NC       South
12    NV   SouthWest
13    AZ   SouthWest
14    NM   SouthWest
15    TX   SouthWest
16    CA  West_Coast
17    OR  West_Coast
18    WA  West_Coast
19    HI  West_Coast
20    AK  West_Coast
21    ID    Mountain
22    UT    Mountain
23    CO    Mountain
24    WY    Mountain
25    MT    Mountain
26    ND      Plains
27    SD      Plains
28    NE      Plains
29    KS      Plains
30    OK      Plains
31    MN     MidWest
32    IA     MidWest
33    MO     MidWest
34    WI     MidWest
35    MI     MidWest
36    IL     MidWest
37    OH     MidWest
38    IN     MidWest
39    PA   NorthEast
40    NY   NorthEast
41    MD   NorthEast
42    DE   NorthEast
43    NJ   NorthEast
44    DC   NorthEast
45    CT   NorthEast
46    RI   NorthEast
47    MA   NorthEast
48    VT   NorthEast
49    ME   NorthEast
50    NH   NorthEast

In [ ]:
us_state_abbrev = {
    'United States': 'USA',
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York City':"NYC",
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto Rico':'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
}